### ISSUE TITLE
Icons missing on Ubuntu 22.04

### ISSUE THREAD

**Issue by leancode** [pbek/hswitch#1]
Just installed it as a snap on Ubuntu 22.04 (LTS) and the icons are missing!
![Screenshot from 2022-12-19 17-23-51](https://user-images.githubusercontent.com/611460/208472692-c65a57be-3fe1-4f51-883d-2eeb06bc422d.png)

Do you know what the problem might be? Something to do with qt5 icons unavailable but I checked: sudo apt list --installed | grep qt5 and it looks all good:

dom@domzb:~/Downloads$ sudo apt list --installed | grep qt5

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libqt5concurrent5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5core5a/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5dbus5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5designer5/jammy,now 5.15.3 -1 amd64 [installed,automatic]
libqt5gui5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5help5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5keychain1/jammy,now 0.13.2-5 amd64 [installed,automatic]
libqt5location5/jammy,now 5.15.3+dfsg-3 amd64 [installed,automatic]
libqt5multimedia5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5multimediawidgets5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5network5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5opengl5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5positioning5/jammy,now 5.15.3+dfsg-3 amd64 [installed,automatic]
libqt5positioningquick5/jammy,now 5.15.3+dfsg-3 amd64 [installed,automatic]
libqt5printsupport5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,a utomatic]
libqt5qml5/jammy,now 5.15.3+dfsg-1 amd64 [installed,automatic]
libqt5qmlmodels5/jammy,now 5.15.3+dfsg-1 amd64 [installed,automatic]
libqt5qmlworkerscript5/jammy,now 5.15.3+dfsg-1 amd64 [installed,automatic]
libqt5quick5/jammy,now 5.15.3+dfsg-1 amd64 [installed,automatic]
libqt5quickcontrols2-5/jammy,now 5.15.3+dfsg-1 amd64 [installed,automatic]
libqt5quicktemplates2-5/jammy,now 5.15.3+dfsg-1 amd64 [installed,automatic]
libqt5quickwidgets5/jammy,now 5.15.3+dfsg-1 amd64 [installed,automatic]
libqt5sensors5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5serialport5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5sql5-sqlite/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5sql5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5svg5/jammy,now 5.15.3 -1 amd64 [installed,automatic]
libqt5test5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5texttospeech5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5waylandclient5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5waylandcompositor5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5webchannel5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5webengine-data/jammy,jammy,now 5.15.9+dfsg-1 all [installed,automatic]
libqt5webengine5/jammy,now 5.15.9+dfsg-1 amd64 [installed,automatic]
libqt5webenginecore5/jammy,now 5.15.9+dfsg-1 amd64 [installed,automatic]
libqt5webenginewidgets5/jammy,now 5.15.9+dfsg-1 amd64 [installed,automatic]
libqt5webkit5/jammy,now 5.212.0~alpha4-15ubuntu1 amd64 [installed,automatic]
libqt5websockets5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5widgets5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5x11extras5/jammy,now 5.15.3-1 amd64 [installed,automatic]
libqt5xml5/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
libqt5xmlpatterns5/jammy,now 5.15.3-1 amd64 [installed,automatic]
python3-pyqt5.qtmultimedia/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtopengl/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtpositioning/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtquick/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtsensors/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtserialport/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtsql/jammy,now 5.15.6+dfsg- 1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtsvg/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qttexttospeech/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtwebchannel/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtwebengine/jammy,now 5.15.5-1 amd64 [installed,automatic]
python3-pyqt5.qtwebkit/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtwebsockets/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.qtxmlpatterns/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
python3-pyqt5.sip/jammy,now 12.9.1-1build1 amd64 [installed,automatic]
python3-pyqt5/jammy,now 5.15.6+dfsg-1ubuntu3 amd64 [installed,automatic]
qt5-gtk-platformtheme/jammy-updates,now 5.15.3+dfsg-2ubuntu0.2 amd64 [installed,automatic]
qt5-image-formats-plugins/jammy,now 5.15.3-1 amd64 [installed,automatic]

 

Any ideas?
 

Thank you.

**Comment by pbek** [comment]
hswitch is relying on free desktop icons , like here:
https://github.com/pbek/hswitch/blob/bb98dbafdaacba0d3f22777f6d5742ab4d443598/src/mainwindow.ui#L145-L146

Seems like https://github.com/pbek/hswitch/blob/develop/build-systems/snap/snapcraft/snapcraft.yaml needs more tinkering.

**Comment by pbek** [comment]
At least I warned about that here 😁 

https://github.com/pbek/hswitch/blob/6273b68cb98e9223eb9a5179001c6f0d40fadaea/README.md?plain=1#L30-L34

**Comment by pbek** [comment]
If you run the snap directly you should now see icons, but still you can't write to the hostfile because of the confinement... So please still run the binary directly (see above). 😉
